/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hf' at '4/20/15 11:01 PM' with Gradle 2.2.1
 *
 * @author hf, @date 4/20/15 11:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
